# Generated by Django 4.0 on 2023-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
