# Generated by Django 4.0 on 2023-08-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movieapp',
        ),
    ]
