# Generated by Django 4.0 on 2023-08-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movieapp', '0005_rename_movie_review_movieapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movieapp',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movieapp'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
